#=================================================
# https://github.com/danxiaonuo/v2ray-okteto
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: 
# Blog: https://www.
#=================================================

# 编译的名称
name: 自动部署okteto

on:
  workflow_dispatch:
  repository_dispatch:

# 编辑文件触发开始编译
#  push:
#    branches:
#      - master
#    paths:
#      - '.github/workflows/ci.yml'


# release发布触发开始编译
#  release:
#    types: published


# 定时触发开始编译(utc时间)
  schedule:
    - cron: '0 1 * * *'


# 点☆Star触发开始编译
#  watch:  
#     types: [started]
     

# 任务集
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    
    # 运行步骤
    steps:
    
    # 准备完毕
    - name: 准备完毕
      uses: actions/checkout@v2
    
    - name: 登录okteto
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "激活命名空间"
      uses: okteto/namespace@master
      with:
        名字: zealup


    - name: "删除管道流程"
      uses: okteto/destroy-pipeline@master
      with:
        namespace: zealup
        name: v2-okteto

        
    - name: "触发流程"
      uses: okteto/pipeline@master
      with:
        namespace: zealup
        name: v2-okteto
        
      
